server:
  port: 8766
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: file://E://学习代码//admin-cloud//admin-cloud
          search-paths: /config/src/main/resources/config/{application}
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/