server:
  port: 8763
spring:
  application:
    name: admin
  security:
    oauth2:
      client:
        registration:
          admin-oidc:
            provider: admin-cloud
            client-id: admin
            client-secret: 123456
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8763/login/oauth2/code/{registrationId}"
            scope: openid
            client-name: admin-oidc
            admin-authorization-code:
              provider: admin-cloud
              client-id: admin
              client-secret: 123456
              authorization-grant-type: authorization_code
              redirect-uri: "http://127.0.0.1:8763/authorized"
              scope: message.read,message.write
              client-name: admin-authorization-code
            admin-credentials:
              provider: admin-cloud
              client-id: admin
              client-secret: 123456
              authorization-grant-type: client_credentials
              scope: message.read,message.write
              client-name: admin-credentials
        provider:
          admin-cloud:
            issuer-uri: http://auth-server:8764
  profiles:
    active: dev

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO