server:
  port: 8761
spring:
  application:
    name: register-server
  profiles:
    active: dev
#  cloud:
#    loadbalancer:
#      ribbon:
#        #        ribbon进入了维护模式，不用ribbon，改用Spring Cloud LoadBalancer
#        enabled: false
eureka:
  instance:
    hostname: localhost
  client:
    #    是否将自己注册到eureka server中，默认为TRUE
    register-with-eureka: false
    #    是否从eureka server中获取注册信息，默认为TRUE
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka