server:
  port: 8762
spring:
  application:
    name: gateway
  cloud:
    gateway:
      httpclient:
        connect-timeout: 1000
        response-timeout: 5s
      #      routes:
      #      - id: admin
      #        uri: lb://admin
      #        predicates:
      #        - Path=/api/admin/**
      #        filters:
      #          - StripPrefix=2
      discovery:
        locator:
          #          转小写，不转小写默认是大写服务名，会匹配不上
          lowerCaseServiceId: true
          #          默认根据eureka服务名路由
          enabled: true
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/