server:
  port: 8767
spring:
  application:
    name: id-generate-server
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/id_generate
    username: root
    password: Root@123
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 1
      max-wait: 60000
      min-idle: 3
      max-active: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/