server:
  port: 8763
spring:
  application:
    name: admin
  security:
    oauth2:
      client:
        registration:
          admin:
            provider: admin
            client-id: admin
            client-secret: 123456
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/