server:
  port: 8763
spring:
  application:
    name: admin
  security:
    oauth2:
      client:
        registration:
          admin:
            provider: admin
            client-id: admin
            client-secret: 123456
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/authorized/admin"
        provider:
          admin:
            authorization-uri: http://localhost:8764/oauth2/authorize
            token-uri: https://your-subdomain.oktapreview.com/oauth2/v1/token
            user-info-uri: https://your-subdomain.oktapreview.com/oauth2/v1/userinfo
            user-name-attribute: sub
            jwk-set-uri: https://your-subdomain.oktapreview.com/oauth2/v1/keys

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/