server:
  port: 8763
spring:
  application:
    name: admin
  security:
    oauth2:
      client:
        registration:
          admin:
            provider: admin-cloud
            client-id: admin
            client-secret: 123456
            client-name: admin
            authorization-grant-type: authorization_code
            scope: openid
            redirect-uri: "{baseUrl}/authorized/admin"
        provider:
          admin-cloud:
            issuer-uri: http://auth-server:8764

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/