server:
  port: 8765
spring:
  application:
    name: uims-server
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-server:8764
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/