server:
  port: 8764
spring:
  application:
    name: authorization-server
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/authorization
    username: root
    password: Root@123
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 1
      max-wait: 60000
      min-idle: 3
      max-active: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
swagger:
  enable: true
springdoc:
  swagger-ui:
    operations-sorter: method
    url: /doc/openapi.json