server:
  port: 8764
spring:
  application:
    name: authorization-server
  profiles:
    active: dev
swagger:
  enable: true
  controller: com.xushifei.authorization.server.controller
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO